### ISSUE TITLE
Not able to add packages

### ISSUE THREAD

**Issue by mramitkumar5495** [plnkr/feedback#78]
When ever I am trying to add any package named it either bootstrap 4 or font-awesome etc, in some scenario it is not even showing the add modal, however in some scenario it showing the modal but not add that package to index.html.

For Example: Below is the log for font-awesome, when I tried to add that in my index.html

  at JSON.parse (<anonymous>)

    at t.<anonymous> (https://cdn.plnkr.co/build/v1.0.0-8-g1cc1a39/runtime.9ff156e16d788666a54a.js:16:58228)

    at x (https://cdn.plnkr.co/build/v1.0.0-8-g1cc1a39/runtime.9ff156e16d788666a54a.js:1:38372)

    at Generator._invoke (https://cdn.plnkr.co/build/v1.0.0-8-g1cc1a39/runtime.9ff156e16d788666a54a.js:1:38160)

    at Generator.t.(anonymous function) [as next] (https://cdn.plnkr.co/build/v1.0.0-8-g1cc1a39/runtime.9ff156e16d788666a54a.js:1:38551)

    at a (https://cdn.plnkr.co/build/v1.0.0-8-g1cc1a39/runtime.9ff156e16d788666a54a.js:16:57020)

    at u (https://cdn.plnkr.co/build/v1.0.0-8-g1cc1a39/runtime.9ff156e16d788666a54a.js:16:57115)

    at <anonymous>

**Comment by ggoodman** [comment]
Thanks for reporting @mramitkumar5495, this is a known issue. I'll close this out once I've fixed it.
